# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: postgres
  host: localhost
  pool: 5
  username: test
  password: test
  port: 5432

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: postgres
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  port: 5432

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: postgres
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  port: 5432
